# check the technical writing for various characteristics
- writing/reflection.md:
    - description: Ensure that reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    # - description: Write a minimum number of 150 meaningful words in the reflection
    #   check: CountFileWords
    #   options:
    #     count: 150
    #     exact: false
    - description: Complete all TODOs, remove the TODO markers in the reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
# check the code file
- source/ml_code.py:
    - description: Ensure that ml_code file exists in the source/ directory
      check: ConfirmFileExists
    # - description: Write a minimum number of 150 meaningful words in the reflection
    #   check: CountFileWords
    #   options:
    #     count: 150
    #     exact: false
    - description: Complete all TODOs, remove the TODO markers in the reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
        

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits (3) in the repository
  check: CountCommits
  options:
    count: 3

